In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup

In [9]:
# creating a target_list for our range from 500 to 700
all_users = pd.read_csv('streamer_df_clean')
targets = all_users[500:700]
target_list = targets.username.to_list()

In [5]:
targets

,username,AVG Viewers,Time Streamed (in hours),Hours Watched,Followers Gained,Total Followers,Total Views,All Time Peak Viewers
500,LatinUp,5096,12.6,64181,946,2267,3151835,22052
501,Reborn_Live,5095,116.2,591922,-1937,1598608,34203255,113707
502,Cabochardlol,5087,17.1,86947,13432,61843,1283207,14384
503,playhearthstonekr,5066,12.0,60747,1754,89594,15830217,41788
504,餐餐自由配,5065,156.9,794619,2578,395643,106225112,38259
...,...,...,...,...,...,...,...,...
695,tarzaned,3942,107.8,424978,5511,453120,21267349,14598
696,AdrianFartade,3942,7.7,30200,4693,85559,1107412,39449
697,Daxak,3934,95.3,375075,4390,158188,15119378,9351
698,OgamingLoL,3930,509.6,2002843,11647,539754,254560765,204222
699,Taylor_Jevaux,3922,91.4,358442,1009563,1441812,21447603,13892

In [8]:
targets

,username,AVG Viewers,Time Streamed (in hours),Hours Watched,Followers Gained,Total Followers,Total Views,All Time Peak Viewers
500,LatinUp,5096,12.6,64181,946,2267,3151835,22052
501,Reborn_Live,5095,116.2,591922,-1937,1598608,34203255,113707
502,Cabochardlol,5087,17.1,86947,13432,61843,1283207,14384
503,playhearthstonekr,5066,12.0,60747,1754,89594,15830217,41788
504,餐餐自由配,5065,156.9,794619,2578,395643,106225112,38259
...,...,...,...,...,...,...,...,...
695,tarzaned,3942,107.8,424978,5511,453120,21267349,14598
696,AdrianFartade,3942,7.7,30200,4693,85559,1107412,39449
697,Daxak,3934,95.3,375075,4390,158188,15119378,9351
698,OgamingLoL,3930,509.6,2002843,11647,539754,254560765,204222
699,Taylor_Jevaux,3922,91.4,358442,1009563,1441812,21447603,13892

In [24]:
def parse_games(usernames):
    '''For all usernames input as a list, retrieve their stats for all games'''
    import time
    t=1
    count = 0
    df_all = pd.DataFrame(columns=['#', 'Avg. viewers', 'Max. viewers', 'Followers', 'Total airtime', 'Last seen', 'User'])
    for user in usernames:
        count += 1
        try:
            user.lower()
            headers = {'User-Agent': 'Mozilla/5.0 (Platform; Security; OS-or-CPU; Localization; rv:1.4) Gecko/20030624 Netscape/7.1 (ax)'}
            response = requests.get(url = f"https://twitchtracker.com/{user}/games", headers=headers)
            soup = BeautifulSoup(response.content, "html.parser")
            df=pd.read_html(str(soup))[0]
            df['User'] = f'{user}'
            df_all = pd.concat([df_all, df])
            if count % 10 == 0:
                print(count)
        except:
            if count % 10 == 0:
                print(count)
            continue
        time.sleep(t)
    return df_all.fillna(0)

In [6]:
def parse_games_2(user_name):
    user_name.lower()
    headers = {'User-Agent': 'Mozilla/5.0 (Platform; Security; OS-or-CPU; Localization; rv:1.4) Gecko/20030624 Netscape/7.1 (ax)'}
    response = requests.get(url = f"https://twitchtracker.com/{user_name}/games", headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    df=pd.read_html(str(soup))[0]
    return df

In [106]:
df = parse_games(target_list)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200

In [11]:
target_list[0]

'LatinUp'

In [107]:
# transfer to gametime
df['Last seen'] = pd.to_datetime(df['Last seen'])
new_dates, new_times = zip(*[(d.date(), d.time()) for d in df['Last seen']])
df = df.assign(new_date=new_dates, new_time=new_times)

In [13]:
test = parse_games_2('LatinUp')

In [108]:
df

,#,Avg. viewers,Max. viewers,Followers,Total airtime,Last seen,User,Game,new_date,new_time
0,#1,4917,22052,58.4 /hour,1726 100%,2021-06-04 01:30:00,LatinUp,Music,2021-06-04,01:30:00
0,#1,19338,80266,747.5 /hour,32940 33%,2020-10-30 00:20:00,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00
1,#2,12478,113707,469.7 /hour,21780 21.8%,2021-06-06 23:40:00,Reborn_Live,Just Chatting,2021-06-06,23:40:00
2,#3,13741,58945,1288.7 /hour,8465 8.5%,2021-01-27 20:20:00,Reborn_Live,Among Us,2021-01-27,20:20:00
3,#4,16088,77378,1221.3 /hour,7811 7.8%,2021-05-25 23:40:00,Reborn_Live,Rust,2021-05-25,23:40:00
...,...,...,...,...,...,...,...,...,...,...
0,#1,874,73101,15.4 /hour,111782 45%,2021-06-04 18:00:00,Warhammer,Warhammer,2021-06-04,18:00:00
1,#2,391,3310,9 /hour,83211 33.5%,2019-01-30 18:20:00,Warhammer,Board Games Live,2019-01-30,18:20:00
2,#3,437,12830,25.6 /hour,51716 20.8%,2019-06-28 19:50:00,Warhammer,Variety,2019-06-28,19:50:00
3,#4,262,491,3.9 /hour,1633 0.7%,2018-01-04 20:50:00,Warhammer,Talk Shows & Podcasts,2018-01-04,20:50:00
4,#5,3088,3088,348 /hour,10 0%,2017-06-02 14:30:00,Warhammer,"Warhammer 40,000: Dawn of War III",2017-06-02,14:30:00

In [114]:
df

,#,Avg. viewers,Max. viewers,Followers,Total airtime,Last seen,User,Game,new_date,new_time
0,#1,4917,22052,58.4 /hour,1726 100%,2021-06-04 01:30:00,LatinUp,Music,2021-06-04,01:30:00
0,#1,19338,80266,747.5 /hour,32940 33%,2020-10-30 00:20:00,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00
1,#2,12478,113707,469.7 /hour,21780 21.8%,2021-06-06 23:40:00,Reborn_Live,Just Chatting,2021-06-06,23:40:00
2,#3,13741,58945,1288.7 /hour,8465 8.5%,2021-01-27 20:20:00,Reborn_Live,Among Us,2021-01-27,20:20:00
3,#4,16088,77378,1221.3 /hour,7811 7.8%,2021-05-25 23:40:00,Reborn_Live,Rust,2021-05-25,23:40:00
...,...,...,...,...,...,...,...,...,...,...
0,#1,874,73101,15.4 /hour,111782 45%,2021-06-04 18:00:00,Warhammer,Warhammer,2021-06-04,18:00:00
1,#2,391,3310,9 /hour,83211 33.5%,2019-01-30 18:20:00,Warhammer,Board Games Live,2019-01-30,18:20:00
2,#3,437,12830,25.6 /hour,51716 20.8%,2019-06-28 19:50:00,Warhammer,Variety,2019-06-28,19:50:00
3,#4,262,491,3.9 /hour,1633 0.7%,2018-01-04 20:50:00,Warhammer,Talk Shows & Podcasts,2018-01-04,20:50:00
4,#5,3088,3088,348 /hour,10 0%,2017-06-02 14:30:00,Warhammer,"Warhammer 40,000: Dawn of War III",2017-06-02,14:30:00

In [115]:
df2 = df['Total airtime']

In [116]:
df.columns = ['Airtime{}'.format(x+1) for x in df2.columns]

AttributeError: 'Series' object has no attribute 'columns'

In [ ]:

new_df.drop(columns=['Total airtime'], inplace=True)
new_df.drop(columns=['Last seen'], inplace=True)
df_all = new_df
df_all['Avg. viewers'] = df_all['Avg. viewers'].apply(lambda x: int(x))
df_all['Max. viewers'] = df_all['Max. viewers'].apply(lambda x: int(x))
df_all['Followers per hour'] = df_all['Followers'].apply(lambda x: x.strip(' /hour'))
df_all.drop(columns=['Followers'], inplace=True)
df_all['Followers per hour'] = df_all['Followers per hour'].apply(lambda x: float(x))
df_all['Airtime %'] = df_all['Airtime2'].apply(lambda x: x.strip('%')).apply(lambda x: float(x) if x else None)

In [103]:
df_all.drop(columns=['Airtime2'], inplace=True)

In [104]:
df_all

,#,Avg. viewers,Max. viewers,User,Game,new_date,new_time,Airtime1,Followers per hour,Airtime %
0,#1,4917,22052,LatinUp,Music,2021-06-04,01:30:00,1726,58.4,100.0
0,#1,19338,80266,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00,32940,747.5,33.0
1,#2,12478,113707,Reborn_Live,Just Chatting,2021-06-06,23:40:00,21780,469.7,21.8
2,#3,13741,58945,Reborn_Live,Among Us,2021-01-27,20:20:00,8465,1288.7,8.5
3,#4,16088,77378,Reborn_Live,Rust,2021-05-25,23:40:00,7811,1221.3,7.8
...,...,...,...,...,...,...,...,...,...,...
0,#1,2683,13892,Taylor_Jevaux,Just Chatting,2021-06-03,23:10:00,41298,2988.2,93.3
1,#2,2813,5581,Taylor_Jevaux,"Pools, Hot Tubs, and Beaches",2021-06-07,00:40:00,2357,562.9,5.3
2,#3,2083,2943,Taylor_Jevaux,Poker,2021-02-25,23:00:00,360,320.7,0.8
3,#4,6,9,Taylor_Jevaux,Call of Duty: Warzone,2020-07-28,19:20:00,145,0.0,0.3
4,#5,4,5,Taylor_Jevaux,Variety,2020-03-17,01:30:00,88,0.7,0.2

In [105]:
df_all.to_csv(r'/Users/home/code/Awesimous/StarFish/notebooks/Games_df', index=False)

In [97]:
df_all.head()

,#,Avg. viewers,Max. viewers,User,Game,new_date,new_time,Airtime1,Airtime2,Followers per hour
0,#1,4917,22052,LatinUp,Music,2021-06-04,01:30:00,1726,100%,58.4
0,#1,19338,80266,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00,32940,33%,747.5
1,#2,12478,113707,Reborn_Live,Just Chatting,2021-06-06,23:40:00,21780,21.8%,469.7
2,#3,13741,58945,Reborn_Live,Among Us,2021-01-27,20:20:00,8465,8.5%,1288.7
3,#4,16088,77378,Reborn_Live,Rust,2021-05-25,23:40:00,7811,7.8%,1221.3

In [78]:
all_df = new_df

In [79]:
all_df.head()

,#,Avg. viewers,Max. viewers,Followers,Last seen,User,Game,new_date,new_time,Airtime1,Airtime2
0,#1,4917,22052,58.4 /hour,2021-06-04 01:30:00,LatinUp,Music,2021-06-04,01:30:00,1726,100%
0,#1,19338,80266,747.5 /hour,2020-10-30 00:20:00,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00,32940,33%
1,#2,12478,113707,469.7 /hour,2021-06-06 23:40:00,Reborn_Live,Just Chatting,2021-06-06,23:40:00,21780,21.8%
2,#3,13741,58945,1288.7 /hour,2021-01-27 20:20:00,Reborn_Live,Among Us,2021-01-27,20:20:00,8465,8.5%
3,#4,16088,77378,1221.3 /hour,2021-05-25 23:40:00,Reborn_Live,Rust,2021-05-25,23:40:00,7811,7.8%

In [89]:
df_all

,#,Avg. viewers,Max. viewers,Followers,User,Game,new_date,new_time,Airtime1,Airtime2,Followers per hour
0,#1,4917,22052,58.4,LatinUp,Music,2021-06-04,01:30:00,1726,100%,58.4
0,#1,19338,80266,747.5,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00,32940,33%,747.5
1,#2,12478,113707,469.7,Reborn_Live,Just Chatting,2021-06-06,23:40:00,21780,21.8%,469.7
2,#3,13741,58945,1288.7,Reborn_Live,Among Us,2021-01-27,20:20:00,8465,8.5%,1288.7
3,#4,16088,77378,1221.3,Reborn_Live,Rust,2021-05-25,23:40:00,7811,7.8%,1221.3
...,...,...,...,...,...,...,...,...,...,...,...
0,#1,2683,13892,2988.2,Taylor_Jevaux,Just Chatting,2021-06-03,23:10:00,41298,93.3%,2988.2
1,#2,2813,5581,562.9,Taylor_Jevaux,"Pools, Hot Tubs, and Beaches",2021-06-07,00:40:00,2357,5.3%,562.9
2,#3,2083,2943,320.7,Taylor_Jevaux,Poker,2021-02-25,23:00:00,360,0.8%,320.7
3,#4,6,9,0,Taylor_Jevaux,Call of Duty: Warzone,2020-07-28,19:20:00,145,0.3%,0
4,#5,4,5,0.7,Taylor_Jevaux,Variety,2020-03-17,01:30:00,88,0.2%,0.7

In [32]:
df_games_all

,#,Avg. viewers,Max. viewers,Followers,Total airtime,Last seen,User,Game,new_date,new_time
0,#1,4917,22052,58.4 /hour,1726 100%,2021-06-04 01:30:00,LatinUp,Music,2021-06-04,01:30:00
0,#1,19338,80266,747.5 /hour,32940 33%,2020-10-30 00:20:00,Reborn_Live,Grand Theft Auto V,2020-10-30,00:20:00
1,#2,12478,113707,469.7 /hour,21780 21.8%,2021-06-06 23:40:00,Reborn_Live,Just Chatting,2021-06-06,23:40:00
2,#3,13741,58945,1288.7 /hour,8465 8.5%,2021-01-27 20:20:00,Reborn_Live,Among Us,2021-01-27,20:20:00
3,#4,16088,77378,1221.3 /hour,7811 7.8%,2021-05-25 23:40:00,Reborn_Live,Rust,2021-05-25,23:40:00
...,...,...,...,...,...,...,...,...,...,...
0,#1,2683,13892,2988.2 /hour,41298 93.3%,2021-06-03 23:10:00,Taylor_Jevaux,Just Chatting,2021-06-03,23:10:00
1,#2,2813,5581,562.9 /hour,2357 5.3%,2021-06-07 00:40:00,Taylor_Jevaux,"Pools, Hot Tubs, and Beaches",2021-06-07,00:40:00
2,#3,2083,2943,320.7 /hour,360 0.8%,2021-02-25 23:00:00,Taylor_Jevaux,Poker,2021-02-25,23:00:00
3,#4,6,9,0 /hour,145 0.3%,2020-07-28 19:20:00,Taylor_Jevaux,Call of Duty: Warzone,2020-07-28,19:20:00
4,#5,4,5,0.7 /hour,88 0.2%,2020-03-17 01:30:00,Taylor_Jevaux,Variety,2020-03-17,01:30:00

In [62]:
df3.Airtime3.fillna(0, inplace=True)